# GitHub Actions Workflow
# WildLife Data Management Pipeline

name: WildLife Pipeline CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      choice:
        description: 'Pipeline choice (1-5)'
        required: true
        default: '1'
        type: choice
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'

env:
  # MinIO Configuration
  MINIO_ENDPOINT: "localhost:9000"
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "password123"
  
  # SonarQube Configuration (set in GitHub Secrets)
  # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  # SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
  
  # HuggingFace Configuration (set in GitHub Secrets)
  # HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}

jobs:
  # Setup and test dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test setup
      run: |
        python orchestrate.py --non-interactive --choice 4
    
    - name: Upload error logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: error-logs-setup
        path: error.log

  # Test individual scripts
  test-scripts:
    runs-on: ubuntu-latest
    needs: setup
    services:
      minio:
        image: minio/minio:latest
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: admin
          MINIO_ROOT_PASSWORD: password123
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval 30s
          --health-timeout 20s
          --health-retries 3
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Wait for MinIO
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:9000/minio/health/live; do sleep 2; done'
    
    - name: Test individual scripts
      run: |
        python orchestrate.py --non-interactive --choice 2
    
    - name: Upload error logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: error-logs-test
        path: error.log

  # Quality control with SonarQube
  quality-control:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
    
    - name: Run quality control
      run: |
        python orchestrate.py --non-interactive --choice 3
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
    
    - name: Upload error logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: error-logs-quality
        path: error.log

  # Deploy complete pipeline
  deploy-pipeline:
    runs-on: ubuntu-latest
    needs: [setup, test-scripts]
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    
    services:
      minio:
        image: minio/minio:latest
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: admin
          MINIO_ROOT_PASSWORD: password123
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval 30s
          --health-timeout 20s
          --health-retries 3
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Wait for MinIO
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:9000/minio/health/live; do sleep 2; done'
    
    - name: Run complete pipeline
      run: |
        python orchestrate.py --non-interactive --choice ${{ github.event.inputs.choice || '1' }}
      env:
        HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
    
    - name: Upload error logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: error-logs-deploy
        path: error.log
    
    - name: Upload pipeline logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pipeline-logs
        path: pipeline.log

  # Cleanup
  cleanup:
    runs-on: ubuntu-latest
    needs: [setup, test-scripts, quality-control, deploy-pipeline]
    if: always()
    
    steps:
    - name: Cleanup
      run: |
        echo "Pipeline completed. Artifacts uploaded."
